### PR TITLE
fix!: editorial review

### PR DESCRIPTION
**Pull request by mfw78**
This PR:

1. Has multiple editorial corrections to converge on standardized nomenclature / terminology.
2. Fixes errors in a code example in `README.md`.
3. Fixes a typographical error for exported interface types (reason for breaking change, per semver).

### CODE REVIEW

**Review by anxolin — APPROVED** [review]
Thanks for the changes! it's a bit embarrassing the number of typos! Thanks 🙏

**Comment by mfw78** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by mfw78** [comment]
Will recreate pull request and ensure eslint / test.

**Pull request closed without merging**
